# Generated by Django 3.1 on 2020-08-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pet Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_location', models.CharField(max_length=250)),
                ('pet_owner_email', models.CharField(max_length=50)),
                ('pet_owner_phone', models.CharField(max_length=11)),
                ('pet_registration_date', models.DateTimeField(auto_now_add=True)),
                ('pet_is_available', models.BooleanField(default=False)),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop_api_app.petcategory')),
            ],
            options={
                'ordering': ['-pet_registration_date', 'pet_category'],
            },
        ),
    ]
