# Generated by Django 3.1 on 2020-08-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_owner_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
