# Generated by Django 3.1 on 2020-08-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_api_app', '0002_pet_pet_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
