# Generated by Django 3.1 on 2020-08-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_api_app', '0003_pet_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcategory',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
